//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.03 at 10:01:17 AM PST 
//


package com.ausland.weixin.model.zhonghuan.xml;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="kdgsname" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="kdgsdh" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="fydh" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="countrytype" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Logisticsback" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="ztai" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="time" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "kdgsname",
    "kdgsdh",
    "fydh",
    "countrytype",
    "logisticsback"
})
@XmlRootElement(name = "back")
public class Back implements Serializable{

    @XmlElement(required = false)
    protected String kdgsname;
    protected String kdgsdh;
    protected String fydh;
    @XmlElement(required = false)
    protected String countrytype;
    @XmlElement(name = "Logisticsback")
    protected List<Logisticsback> logisticsback;

    /**
     * Gets the value of the kdgsname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKdgsname() {
        return kdgsname;
    }

    /**
     * Sets the value of the kdgsname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKdgsname(String value) {
        this.kdgsname = value;
    }

    /**
     * Gets the value of the kdgsdh property.
     * 
     */
    public String getKdgsdh() {
        return kdgsdh;
    }

    /**
     * Sets the value of the kdgsdh property.
     * 
     */
    public void setKdgsdh(String value) {
        this.kdgsdh = value;
    }

    /**
     * Gets the value of the fydh property.
     * 
     */
    public String getFydh() {
        return fydh;
    }

    /**
     * Sets the value of the fydh property.
     * 
     */
    public void setFydh(String value) {
        this.fydh = value;
    }

    /**
     * Gets the value of the countrytype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCountrytype() {
        return countrytype;
    }

    /**
     * Sets the value of the countrytype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCountrytype(String value) {
        this.countrytype = value;
    }

    /**
     * Gets the value of the logisticsback property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the logisticsback property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLogisticsback().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Back.Logisticsback }
     * 
     * 
     */
    public List<Logisticsback> getLogisticsback() {
        if (logisticsback == null) {
            logisticsback = new ArrayList<Logisticsback>();
        }
        return this.logisticsback;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="ztai" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="time" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "ztai",
        "time"
    })
    public static class Logisticsback  implements Serializable{

        @XmlElement(required = false)
        protected String ztai;
        @XmlElement(required = false)
        protected String time;

        /**
         * Gets the value of the ztai property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getZtai() {
            return ztai;
        }

        /**
         * Sets the value of the ztai property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setZtai(String value) {
            this.ztai = value;
        }

        /**
         * Gets the value of the time property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTime() {
            return time;
        }

        /**
         * Sets the value of the time property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTime(String value) {
            this.time = value;
        }

    }

}
