//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.08 at 10:47:24 PM PST 
//


package com.ausland.weixin.model.zhonghuan.xml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="message" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="issuccess" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="fydhlist" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="chrlrsj" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="chrfydh" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *                   &lt;element name="chrbgdh" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="chrzl" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
 *                   &lt;element name="chrshzt" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="ckdhm" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="chrsjr" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="chrsjrdz" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="chrsjrdh" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="njxx" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="chrggxh" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="chrpp" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="chrpm" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="chrjs" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "message",
    "issuccess",
    "fydhlist"
})
@XmlRootElement(name = "tel")
public class Tel {

    protected String message;
    @XmlElement(required = true)
    protected String issuccess;
    protected List<Tel.Fydh> fydhlist;

    /**
     * Gets the value of the message property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMessage() {
        return message;
    }

    /**
     * Sets the value of the message property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMessage(String value) {
        this.message = value;
    }

    /**
     * Gets the value of the issuccess property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIssuccess() {
        return issuccess;
    }

    /**
     * Sets the value of the issuccess property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIssuccess(String value) {
        this.issuccess = value;
    }

    /**
     * Gets the value of the fydhlist property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the fydhlist property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFydhlist().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Tel.Fydhlist }
     * 
     * 
     */
    public List<Tel.Fydh> getFydhlist() {
        if (fydhlist == null) {
            fydhlist = new ArrayList<Tel.Fydh>();
        }
        return this.fydhlist;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="chrlrsj" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="chrfydh" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
     *         &lt;element name="chrbgdh" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="chrzl" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="chrshzt" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="ckdhm" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="chrsjr" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="chrsjrdz" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="chrsjrdh" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="njxx" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="chrggxh" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="chrpp" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="chrpm" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="chrjs" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "chrlrsj",
        "chrfydh",
        "chrbgdh",
        "chrzl",
        "chrshzt",
        "ckdhm",
        "chrsjr",
        "chrsjrdz",
        "chrsjrdh",
        "njxx"
    })
    public static class Fydh {

        protected String chrlrsj;
        protected String chrfydh;
        protected String chrbgdh;
        protected String chrzl;
        protected String chrshzt;
        protected String ckdhm;
        protected String chrsjr;
        protected String chrsjrdz;
        protected String chrsjrdh;
        protected List<Tel.Fydh.Njxx> njxx;

        /**
         * Gets the value of the chrlrsj property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getChrlrsj() {
            return chrlrsj;
        }

        /**
         * Sets the value of the chrlrsj property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setChrlrsj(String value) {
            this.chrlrsj = value;
        }

        /**
         * Gets the value of the chrfydh property.
         * 
         * @return
         *     possible object is
         *     {@link Long }
         *     
         */
        public String getChrfydh() {
            return chrfydh;
        }

        /**
         * Sets the value of the chrfydh property.
         * 
         * @param value
         *     allowed object is
         *     {@link Long }
         *     
         */
        public void setChrfydh(String value) {
            this.chrfydh = value;
        }

        /**
         * Gets the value of the chrbgdh property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getChrbgdh() {
            return chrbgdh;
        }

        /**
         * Sets the value of the chrbgdh property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setChrbgdh(String value) {
            this.chrbgdh = value;
        }

        /**
         * Gets the value of the chrzl property.
         * 
         * @return
         *     possible object is
         *     {@link Float }
         *     
         */
        public String getChrzl() {
            return chrzl;
        }

        /**
         * Sets the value of the chrzl property.
         * 
         * @param value
         *     allowed object is
         *     {@link Float }
         *     
         */
        public void setChrzl(String value) {
            this.chrzl = value;
        }

        /**
         * Gets the value of the chrshzt property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getChrshzt() {
            return chrshzt;
        }

        /**
         * Sets the value of the chrshzt property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setChrshzt(String value) {
            this.chrshzt = value;
        }

        /**
         * Gets the value of the ckdhm property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCkdhm() {
            return ckdhm;
        }

        /**
         * Sets the value of the ckdhm property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCkdhm(String value) {
            this.ckdhm = value;
        }

        /**
         * Gets the value of the chrsjr property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getChrsjr() {
            return chrsjr;
        }

        /**
         * Sets the value of the chrsjr property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setChrsjr(String value) {
            this.chrsjr = value;
        }

        /**
         * Gets the value of the chrsjrdz property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getChrsjrdz() {
            return chrsjrdz;
        }

        /**
         * Sets the value of the chrsjrdz property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setChrsjrdz(String value) {
            this.chrsjrdz = value;
        }

        /**
         * Gets the value of the chrsjrdh property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getChrsjrdh() {
            return chrsjrdh;
        }

        /**
         * Sets the value of the chrsjrdh property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setChrsjrdh(String value) {
            this.chrsjrdh = value;
        }

        /**
         * Gets the value of the njxx property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the njxx property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getNjxx().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Tel.Fydhlist.Njxx }
         * 
         * 
         */
        public List<Tel.Fydh.Njxx> getNjxx() {
            if (njxx == null) {
                njxx = new ArrayList<Tel.Fydh.Njxx>();
            }
            return this.njxx;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="chrggxh" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="chrpp" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="chrpm" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="chrjs" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "chrggxh",
            "chrpp",
            "chrpm",
            "chrjs"
        })
        public static class Njxx {

            protected String chrggxh;
            protected String chrpp;
            protected String chrpm;
            protected String chrjs;

            /**
             * Gets the value of the chrggxh property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getChrggxh() {
                return chrggxh;
            }

            /**
             * Sets the value of the chrggxh property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setChrggxh(String value) {
                this.chrggxh = value;
            }

            /**
             * Gets the value of the chrpp property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getChrpp() {
                return chrpp;
            }

            /**
             * Sets the value of the chrpp property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setChrpp(String value) {
                this.chrpp = value;
            }

            /**
             * Gets the value of the chrpm property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getChrpm() {
                return chrpm;
            }

            /**
             * Sets the value of the chrpm property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setChrpm(String value) {
                this.chrpm = value;
            }

            /**
             * Gets the value of the chrjs property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getChrjs() {
                return chrjs;
            }

            /**
             * Sets the value of the chrjs property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setChrjs(String value) {
                this.chrjs = value;
            }

        }

    }

}
