//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.03 at 10:00:13 AM PST 
//


package com.ausland.weixin.model.zhonghuan.xml;

import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="message" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="issuccess" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="fydhlist">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="chrfydh" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *                   &lt;element name="chrdysj" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "message",
    "issuccess",
    "fydhlist"
})
@XmlRootElement(name = "tel")
public class Tel {

 
    protected String message;
    @XmlElement(required = true)
    protected String issuccess;
 
    protected List<Fydh> fydhlist;

    /**
     * Gets the value of the message property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMessage() {
        return message;
    }

    /**
     * Sets the value of the message property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMessage(String value) {
        this.message = value;
    }

    /**
     * Gets the value of the issuccess property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIssuccess() {
        return issuccess;
    }

    /**
     * Sets the value of the issuccess property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIssuccess(String value) {
        this.issuccess = value;
    }

    /**
     * Gets the value of the fydhlist property.
     * 
     * @return
     *     possible object is
     *     {@link Tel.Fydhlist }
     *     
     */
    public List<Fydh> getFydhlist() {
        return fydhlist;
    }

    /**
     * Sets the value of the fydhlist property.
     * 
     * @param value
     *     allowed object is
     *     {@link Tel.Fydhlist }
     *     
     */
    public void setFydhlist(List<Fydh> value) {
        this.fydhlist = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="chrfydh" type="{http://www.w3.org/2001/XMLSchema}long"/>
     *         &lt;element name="chrdysj" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "chrfydh",
        "chrdysj"
    })
    public static class Fydh{

        protected String chrfydh;
     
        protected String chrdysj;

        /**
         * Gets the value of the chrfydh property.
         * 
         */
        public String getChrfydh() {
            return chrfydh;
        }

        /**
         * Sets the value of the chrfydh property.
         * 
         */
        public void setChrfydh(String value) {
            this.chrfydh = value;
        }

        /**
         * Gets the value of the chrdysj property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getChrdysj() {
            return chrdysj;
        }

        /**
         * Sets the value of the chrdysj property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setChrdysj(String value) {
            this.chrdysj = value;
        }

    }

}
