
package com.ausland.weixin.model.zhonghuan.wsdl;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.11
 * 2018-03-03T08:40:32.753-08:00
 * Generated source version: 3.1.11
 */

@WebFault(name = "IllegalAccessException", targetNamespace = "http://zh.au.service.LogisticsServiceI.com")
public class IllegalAccessException_Exception extends Exception {
    
    private com.ausland.weixin.model.zhonghuan.wsdl.IllegalAccessException illegalAccessException;

    public IllegalAccessException_Exception() {
        super();
    }
    
    public IllegalAccessException_Exception(String message) {
        super(message);
    }
    
    public IllegalAccessException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public IllegalAccessException_Exception(String message, com.ausland.weixin.model.zhonghuan.wsdl.IllegalAccessException illegalAccessException) {
        super(message);
        this.illegalAccessException = illegalAccessException;
    }

    public IllegalAccessException_Exception(String message, com.ausland.weixin.model.zhonghuan.wsdl.IllegalAccessException illegalAccessException, Throwable cause) {
        super(message, cause);
        this.illegalAccessException = illegalAccessException;
    }

    public com.ausland.weixin.model.zhonghuan.wsdl.IllegalAccessException getFaultInfo() {
        return this.illegalAccessException;
    }
}
