
package com.ausland.weixin.model.zhonghuan.wsdl;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.11
 * 2018-03-03T08:40:32.759-08:00
 * Generated source version: 3.1.11
 */

@WebFault(name = "InvocationTargetException", targetNamespace = "http://zh.au.service.LogisticsServiceI.com")
public class InvocationTargetException_Exception extends Exception {
    
    private com.ausland.weixin.model.zhonghuan.wsdl.InvocationTargetException invocationTargetException;

    public InvocationTargetException_Exception() {
        super();
    }
    
    public InvocationTargetException_Exception(String message) {
        super(message);
    }
    
    public InvocationTargetException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public InvocationTargetException_Exception(String message, com.ausland.weixin.model.zhonghuan.wsdl.InvocationTargetException invocationTargetException) {
        super(message);
        this.invocationTargetException = invocationTargetException;
    }

    public InvocationTargetException_Exception(String message, com.ausland.weixin.model.zhonghuan.wsdl.InvocationTargetException invocationTargetException, Throwable cause) {
        super(message, cause);
        this.invocationTargetException = invocationTargetException;
    }

    public com.ausland.weixin.model.zhonghuan.wsdl.InvocationTargetException getFaultInfo() {
        return this.invocationTargetException;
    }
}
