package com.ausland.weixin.model.zhonghuan.wsdl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.11
 * 2018-03-03T08:40:32.780-08:00
 * Generated source version: 3.1.11
 * 
 */
@WebServiceClient(name = "LogisticsServiceImplService", 
                  wsdlLocation = "file:/C:/Tools/apache-cxf-3.1.11/zhonghuan/zhonghuanlogisticsservice.wsdl",
                  targetNamespace = "http://impl.common.zh.com/") 
public class LogisticsServiceImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://impl.common.zh.com/", "LogisticsServiceImplService");
    public final static QName LogisticsServiceImplPort = new QName("http://impl.common.zh.com/", "LogisticsServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Tools/apache-cxf-3.1.11/zhonghuan/zhonghuanlogisticsservice.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(LogisticsServiceImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/C:/Tools/apache-cxf-3.1.11/zhonghuan/zhonghuanlogisticsservice.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public LogisticsServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public LogisticsServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public LogisticsServiceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public LogisticsServiceImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public LogisticsServiceImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public LogisticsServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns LogisticsServiceI
     */
    @WebEndpoint(name = "LogisticsServiceImplPort")
    public LogisticsServiceI getLogisticsServiceImplPort() {
        return super.getPort(LogisticsServiceImplPort, LogisticsServiceI.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns LogisticsServiceI
     */
    @WebEndpoint(name = "LogisticsServiceImplPort")
    public LogisticsServiceI getLogisticsServiceImplPort(WebServiceFeature... features) {
        return super.getPort(LogisticsServiceImplPort, LogisticsServiceI.class, features);
    }

}
