
package com.ausland.weixin.model.zhonghuan.wsdl;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.11
 * 2018-03-03T08:40:32.663-08:00
 * Generated source version: 3.1.11
 * 
 */
public final class LogisticsServiceI_LogisticsServiceImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://impl.common.zh.com/", "LogisticsServiceImplService");

    private LogisticsServiceI_LogisticsServiceImplPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = LogisticsServiceImplService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        LogisticsServiceImplService ss = new LogisticsServiceImplService(wsdlURL, SERVICE_NAME);
        LogisticsServiceI port = ss.getLogisticsServiceImplPort();  
        
        {
        System.out.println("Invoking getYtLoggistics...");
        java.lang.String _getYtLoggistics_fydh = "";
        try {
            java.lang.String _getYtLoggistics__return = port.getYtLoggistics(_getYtLoggistics_fydh);
            System.out.println("getYtLoggistics.result=" + _getYtLoggistics__return);

        } catch (NoSuchMethodException_Exception e) { 
            System.out.println("Expected exception: NoSuchMethodException has occurred.");
            System.out.println(e.toString());
        } catch (IllegalAccessException_Exception e) { 
            System.out.println("Expected exception: IllegalAccessException has occurred.");
            System.out.println(e.toString());
        } catch (InvocationTargetException_Exception e) { 
            System.out.println("Expected exception: InvocationTargetException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getTeltoFydh...");
        java.lang.String _getTeltoFydh_chrsjrdh = "";
        java.lang.String _getTeltoFydh_username = "";
        java.lang.String _getTeltoFydh_password = "";
        java.lang.String _getTeltoFydh_didbh = "";
        java.lang.String _getTeltoFydh__return = port.getTeltoFydh(_getTeltoFydh_chrsjrdh, _getTeltoFydh_username, _getTeltoFydh_password, _getTeltoFydh_didbh);
        System.out.println("getTeltoFydh.result=" + _getTeltoFydh__return);


        }
        {
        System.out.println("Invoking getLogisticsInformation...");
        java.lang.String _getLogisticsInformation_fydh = "";
        java.lang.String _getLogisticsInformation_countrytype = "";
        try {
            java.lang.String _getLogisticsInformation__return = port.getLogisticsInformation(_getLogisticsInformation_fydh, _getLogisticsInformation_countrytype);
            System.out.println("getLogisticsInformation.result=" + _getLogisticsInformation__return);

        } catch (NoSuchMethodException_Exception e) { 
            System.out.println("Expected exception: NoSuchMethodException has occurred.");
            System.out.println(e.toString());
        } catch (IllegalAccessException_Exception e) { 
            System.out.println("Expected exception: IllegalAccessException has occurred.");
            System.out.println(e.toString());
        } catch (InvocationTargetException_Exception e) { 
            System.out.println("Expected exception: InvocationTargetException has occurred.");
            System.out.println(e.toString());
        }
            }

        System.exit(0);
    }

}
