
package com.ausland.weixin.model.zhonghuan.wsdl;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.11
 * 2018-03-03T08:40:32.745-08:00
 * Generated source version: 3.1.11
 */

@WebFault(name = "NoSuchMethodException", targetNamespace = "http://zh.au.service.LogisticsServiceI.com")
public class NoSuchMethodException_Exception extends Exception {
    
    private com.ausland.weixin.model.zhonghuan.wsdl.NoSuchMethodException noSuchMethodException;

    public NoSuchMethodException_Exception() {
        super();
    }
    
    public NoSuchMethodException_Exception(String message) {
        super(message);
    }
    
    public NoSuchMethodException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public NoSuchMethodException_Exception(String message, com.ausland.weixin.model.zhonghuan.wsdl.NoSuchMethodException noSuchMethodException) {
        super(message);
        this.noSuchMethodException = noSuchMethodException;
    }

    public NoSuchMethodException_Exception(String message, com.ausland.weixin.model.zhonghuan.wsdl.NoSuchMethodException noSuchMethodException, Throwable cause) {
        super(message, cause);
        this.noSuchMethodException = noSuchMethodException;
    }

    public com.ausland.weixin.model.zhonghuan.wsdl.NoSuchMethodException getFaultInfo() {
        return this.noSuchMethodException;
    }
}
